### ISSUE TITLE
buildEventDay.py not found

### ISSUE THREAD

**Issue by NeuroGliaLab** [fdechaumont/lmt-analysis#19]
In a previous release of the lmt-analysis repo, the function BuildEventDays could be used to parse events happening during the day. Now, I cannot find this anywhere. Has this been integrated to another class and removed?

**Comment by fdechaumont** [comment]
Hi NeuroGliaLab, 

I am going to check on that. Note that there is BuildEventNight, maybe it has been cleanup because it was redundant with that one.

**Comment by NeuroGliaLab** [comment]
That is what I thought might have been the case, but I wanted to check. Thanks for updating us.

**Comment by fdechaumont** [comment]
I am surprised, I checked on the whole history of this git, I did not see a file called buildEventDay or something similar.
maybe @ntorquet knows about this as he wrote the buildEventNight
@NeuroGliaLab can you send me an email ? I will give you access to another support level that I am experimenting

**Comment by ntorquet** [comment]
Hello,
I have no memory of seeing a buildEventDays function or file. I will ask to @elodieey .

**Comment by elodieey** [comment]
Hi,
I do not remember any script with this name. There is a BuidEventNight.py script (with a typo...), but I do not use it. And I do not think it is for the purpose you are looking for. Sorry.

**Comment by fdechaumont** [comment]
So it seems we never had it. I close the topic as an issue.
Best

**Comment by NeuroGliaLab** [comment]
Thank you for the quick reply we are still trying to figure out how the different files work together.

**Comment by fdechaumont** [comment]
Please send me an email so that I can help you more

**Comment by NeuroGliaLab** [comment]
Could you provide me with your email address? Thanks
