### ISSUE TITLE
[ComputeMeasuresIdentityProfileOneMouseAutomatic] problem with output header

### ISSUE THREAD

**Issue by alex6416** [fdechaumont/lmt-analysis#5]
Hello
When I ran this script ComputeMeasuresIdentityProfileOneMouseAutomatic.
User1 appear in header at line 109 but is not set in the table which shift data. This can be fix by removing user1 at line 109. 

Goodbye

Alexandre Maïsterrena

**Comment by fdechaumont** [comment]
Dear alex6416

Thanks for your feedback

This is now fixed.

Best

Fab
